tests: factor name of output files into a variable
* tests/case-fold-backref, tests/case-fold-char-class,
tests/case-fold-char-range, tests/case-fold-char-type,
tests/dfaexec-multibyte: Use a variable for the output filename,
as it is common to the grep and compare invocations.

diff --git a/tests/case-fold-char-range b/tests/case-fold-char-range
--- a/tests/case-fold-char-range
+++ b/tests/case-fold-char-range
@@ -7,16 +7,18 @@ printf 'A\nZ\n'      > exp1 || framework_failure
 fail=0
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf 'A\n1\nZ\n.\n' | LC_ALL=$LOC grep -i '[a-z]' > out1-$LOC || fail=1
-  compare out1-$LOC exp1 || fail=1
+  out=out1-$LOC
+  printf 'A\n1\nZ\n.\n' | LC_ALL=$LOC grep -i '[a-z]' > $out || fail=1
+  compare $out exp1 || fail=1
 done
 
 # This actually passes also for grep-2.5.3
 printf 'a\nz\n'      > exp2 || framework_failure
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf 'a\n1\nz\n.\n' | LC_ALL=$LOC grep -i '[A-Z]' > out2-$LOC || fail=1
-  compare out2-$LOC exp2 || fail=1
+  out=out2-$LOC
+  printf 'a\n1\nz\n.\n' | LC_ALL=$LOC grep -i '[A-Z]' > $out || fail=1
+  compare $out exp2 || fail=1
 done
 
 Exit $fail
diff --git a/tests/case-fold-char-type b/tests/case-fold-char-type
--- a/tests/case-fold-char-type
+++ b/tests/case-fold-char-type
@@ -7,15 +7,17 @@ printf 'Y\n'      > exp1 || framework_failure
 fail=0
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf '1\nY\n.\n' | LC_ALL=$LOC grep -i '[[:lower:]]' > out1-$LOC || fail=1
-  compare out1-$LOC exp1 || fail=1
+  out=out1-$LOC
+  printf '1\nY\n.\n' | LC_ALL=$LOC grep -i '[[:lower:]]' > $out || fail=1
+  compare $out exp1 || fail=1
 done
 
 printf 'y\n'      > exp2 || framework_failure
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf '1\ny\n.\n' | LC_ALL=$LOC grep -i '[[:upper:]]' > out2-$LOC || fail=1
-  compare out2-$LOC exp2 || fail=1
+  out=out2-$LOC
+  printf '1\ny\n.\n' | LC_ALL=$LOC grep -i '[[:upper:]]' > $out || fail=1
+  compare $out exp2 || fail=1
 done
 
 Exit $fail
