tests: use different output files to simplify reading failed .log files
* tests/case-fold-backref, tests/case-fold-char-class,
tests/case-fold-char-range, tests/case-fold-char-type: Use a different
name for each output file from grep.
* tests/dfaexec-multibyte: Likewise, and merge some grep invocations.

diff --git a/tests/case-fold-char-class b/tests/case-fold-char-class
--- a/tests/case-fold-char-class
+++ b/tests/case-fold-char-class
@@ -7,15 +7,15 @@ printf 'Y\n'      > exp1 || framework_failure
 fail=0
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf 'X\nY\nZ\n' | LC_ALL=$LOC grep -i '[y]' > out1 || fail=1
-  compare out1 exp1 || fail=1
+  printf 'X\nY\nZ\n' | LC_ALL=$LOC grep -i '[y]' > out1-$LOC || fail=1
+  compare out1-$LOC exp1 || fail=1
 done
 
 printf 'y\n'      > exp2 || framework_failure
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf 'x\ny\nz\n' | LC_ALL=$LOC grep -i '[Y]' > out2 || fail=1
-  compare out2 exp2 || fail=1
+  printf 'x\ny\nz\n' | LC_ALL=$LOC grep -i '[Y]' > out2-$LOC || fail=1
+  compare out2-$LOC exp2 || fail=1
 done
 
 Exit $fail
diff --git a/tests/case-fold-char-range b/tests/case-fold-char-range
--- a/tests/case-fold-char-range
+++ b/tests/case-fold-char-range
@@ -7,16 +7,16 @@ printf 'A\nZ\n'      > exp1 || framework_failure
 fail=0
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf 'A\n1\nZ\n.\n' | LC_ALL=$LOC grep -i '[a-z]' > out1 || fail=1
-  compare out1 exp1 || fail=1
+  printf 'A\n1\nZ\n.\n' | LC_ALL=$LOC grep -i '[a-z]' > out1-$LOC || fail=1
+  compare out1-$LOC exp1 || fail=1
 done
 
 # This actually passes also for grep-2.5.3
 printf 'a\nz\n'      > exp2 || framework_failure
 
 for LOC in en_US.UTF-8 zh_CN $LOCALE_FR_UTF8; do
-  printf 'a\n1\nz\n.\n' | LC_ALL=$LOC grep -i '[A-Z]' > out2 || fail=1
-  compare out2 exp2 || fail=1
+  printf 'a\n1\nz\n.\n' | LC_ALL=$LOC grep -i '[A-Z]' > out2-$LOC || fail=1
+  compare out2-$LOC exp2 || fail=1
 done
 
 Exit $fail
