tests: fix char-class-multibyte
* tests/char-class-multibyte: Make it pass.

diff --git a/tests/char-class-multibyte b/tests/char-class-multibyte
--- a/tests/char-class-multibyte
+++ b/tests/char-class-multibyte
@@ -3,20 +3,20 @@
 : ${srcdir=.}
 . "$srcdir/init.sh"; path_prepend_ ../src
 
-printf 'É\n'      > exp1 || framework_failure
+printf 'é\n'      > exp1 || framework_failure
 fail=0
 
 for LOC in en_US.UTF-8 $LOCALE_FR_UTF8; do
   out=out1-$LOC
-  printf 'á\nç\nÉ\n' | LC_ALL=$LOC grep '[é]' > $out || fail=1
+  printf 'á\nç\né\n' | LC_ALL=$LOC grep '[é]' > $out || fail=1
   compare $out exp1 || fail=1
 done
 
-printf 'é\n'      > exp2 || framework_failure
+printf 'É\n'      > exp2 || framework_failure
 
 for LOC in en_US.UTF-8 $LOCALE_FR_UTF8; do
   out=out2-$LOC
-  printf 'á\nç\né\n' | LC_ALL=$LOC grep '[É]' > $out || fail=1
+  printf 'Á\nÇ\nÉ\n' | LC_ALL=$LOC grep '[É]' > $out || fail=1
   compare $out exp2 || fail=1
 done
 
