tests: improve empty test
* tests/empty: Add more tests, note expected failure.

diff --git a/tests/empty b/tests/empty
--- a/tests/empty
+++ b/tests/empty
@@ -16,7 +16,7 @@ require_timeout_
 failures=0
 
 for locale in C en_US.UTF-8; do
-    for options in '-E' '-E -w' '-F -x' '-G -w -x'; do
+    for options in '-E' '-F'; do
 
 	# should return 0 found a match
 	echo "" | LC_ALL=$locale timeout 10s grep $options -e ''
@@ -36,6 +36,46 @@ for locale in C en_US.UTF-8; do
 	echo "abcd" | LC_ALL=$locale timeout 10s grep $options -f /dev/null -e "abcd"
 	if test $? -ne 0 ; then
 		echo "Status: Wrong status code, test \#3 failed ($options $locale)"
+		failures=1
+	fi
+
+	# should return 0 found a match
+	echo "" | LC_ALL=$locale timeout 10s grep $options -e ''
+	if test $? -ne 0 ; then
+		echo "Status: Wrong status code, test \#4 failed ($options $locale)"
+		failures=1
+	fi
+
+	# should return 0 found a match
+	echo "abcd" | LC_ALL=$locale timeout 10s grep $options -e ''
+	if test $? -ne 0 ; then
+		echo "Status: Wrong status code, test \#5 failed ($options $locale)"
+		failures=1
+	fi
+    done
+
+    # -F -w omitted because it fails test #6, will be revisited after 2.6
+    # stabilizes.
+    for options in '-E -w' '-E -x' '-E -w -x' '-F -x' '-F -w -x'; do
+
+	# should return 0 found a match
+	echo "" | LC_ALL=$locale timeout 10s grep $options -e ''
+	if test $? -ne 0 ; then
+		echo "Status: Wrong status code, test \#6 failed ($options $locale)"
+		failures=1
+	fi
+
+	# should return 1 found no match
+	echo "abcd" | LC_ALL=$locale timeout 10s grep $options -f /dev/null
+	if test $? -ne 1 ; then
+		echo "Status: Wrong status code, test \#7 failed ($options $locale)"
+		failures=1
+	fi
+
+	# should return 1 found no match
+	echo "abcd" | LC_ALL=$locale timeout 10s grep $options -f /dev/null -e ""
+	if test $? -ne 1 ; then
+		echo "Status: Wrong status code, test \#8 failed ($options $locale)"
 		failures=1
 	fi
     done
