Omit excess "Binary file ... matches"
Problem reported in: http://bugs.gnu.org/22461
* src/grep.c (grep): Don't report "Binary file ... matches"
merely because the file contained both matches and binary data.
Insist that the binary data contained a match.
* tests/null-byte: Add a test for this.

diff --git a/tests/null-byte b/tests/null-byte
--- a/tests/null-byte
+++ b/tests/null-byte
@@ -51,4 +51,9 @@ for left in '' a '#' '\0'; do
   done
 done
 
+(echo xxx && yes yyy | sed 100000q && printf '\0') >in || framework_failure_
+echo xxx >exp || framework_failure_
+grep xxx in >out || fail=1
+compare exp out || fail=1
+
 Exit $fail
