tests: clean up pcre
* tests/pcre: Skip (don't pass) the test when PCRE support is disabled.
Don't redirect so much to /dev/null, now that all test output goes to
pcre.log.  Remove unnecessary braces and diagnostic about failing test.

diff --git a/tests/pcre b/tests/pcre
--- a/tests/pcre
+++ b/tests/pcre
@@ -1,5 +1,5 @@
 #! /bin/sh
-# Regression test for GNU grep.
+# Ensure that with -P, \s*$ matches a newline.
 #
 # Copyright (C) 2001, 2006, 2009-2011 Free Software Foundation, Inc.
 #
@@ -10,14 +10,11 @@
 . "${srcdir=.}/init.sh"; path_prepend_ ../src
 
 # Test that grep was compiled with HAVE_LIBPCRE.  Otherwise, pass.
-echo . | grep -P . >/dev/null 2>&1 || exit 0
+echo . | grep -P . || skip_ no PCRE support
 
 fail=0
-ft=
 
 # See CVS revision 1.32 of "src/search.c".
-echo | { grep -P '\s*$'; } > /dev/null 2>&1 || { ft="$ft 1"; fail=1; }
-
-test "x$ft" != x && echo "Failed PCRE tests:$ft"
+echo | grep -P '\s*$' || fail=1
 
 Exit $fail
