tests: pcre-jitstack: avoid false failure without base64 -d support
* tests/pcre-jitstack: Try harder to find a base64 decoder:
try 'base64 -d', 'base64 -D', 'openssl base64 -d' and perl's
MIME::Base64 decode_base64.  The old code would fail at least on
OS X, for which base64 expects -D or --decode.
Reported by Jack Howarth in http://bugs.gnu.org/24243.

diff --git a/tests/pcre-jitstack b/tests/pcre-jitstack
--- a/tests/pcre-jitstack
+++ b/tests/pcre-jitstack
@@ -10,14 +10,22 @@
 . "${srcdir=.}/init.sh"; path_prepend_ ../src
 require_pcre_
 
-nl_base64=$(echo | (base64) 2>/dev/null) && test "X$nl_base64" = XCg== ||
-  skip_ "your system lacks the base64 program"
-foo=$( (echo foo | gzip | gzip -d) 2>/dev/null) && test "X$foo" = Xfoo ||
-  skip_ "your system lacks the gzip program"
+for p in 'base64 -d' 'base64 -D' 'openssl base64 -d' \
+      "perl -MMIME::Base64 -0777ne 'print decode_base64(\$_)'" FAIL; do
+    test "$p" = FAIL && skip_ "your system lacks a base64 decoder"
+    x=$(echo eA==| ( eval "$p" ) 2>/dev/null) && test "X$x" = Xx &&
+      {
+        eval "b64_decode() { $p; }"
+        break
+      }
+done
+
+foo=$( (echo foo | gzip | gzip -d) 2>/dev/null) && test "X$foo" = Xfoo \
+  || skip_ "your system lacks the gzip program"
 
 fail=0
 
-base64 -d >pcrejit.txt.gz <<'EOF'
+b64_decode >pcrejit.txt.gz <<'EOF' || framework_failure_
 H4sIAAAAAAACA+2bUU4DMQxE/7mMz5T7XwKE+IBKVLue58yk0B9EtX6xJxN7t4VaH69a6+tHrW+/
 r4e3n75KARWShSOFTtiumE3FPVyo79ATIJ0Ry0No/yXe99UIUqTGKKUzYHFJHJoaCONQDCnDSCDS
 IPAvGCVeXNsZ7lpbWFfdaZtgPos5LeK2C1TBKzD09V3HFlCOsbFT/hNbz4HzJaRjnjdam9FXw/o6
@@ -29,14 +37,13 @@ dkcKkYUglER2Q4L4gnmOiNGzSBATwGQgwihs5/QffIhyfg4hJvM2r4Rp6L+1ibCCd4jYZ6jCiBlc
 2+y4fl4yTGIwcWXNAUEeXmu8iCMV96DNTnmRNICDk2N5qaXGbsF91OX/0hlcYTjrMfy02p9Xv70D
 mv3RZCFOAAA=
 EOF
-test $? -eq 0 || framework_failure_
 
 gzip -d pcrejit.txt || framework_failure_
 
 LC_ALL=C grep -P -n '^([/](?!/)|[^/])*~/.*' pcrejit.txt
 if test $? != 1; then
     # The above often makes grep attempt to use an inordinate amount
-    # of stack space.  If grep fails with $? != 1, try gain, but this
+    # of stack space.  If grep fails with $? != 1, try again, but this
     # time with no soft limit:
 
     # Use ulimit to remove that limit, if possible.
