tests: fix surrogate-pair test to work on 16-bit wchar_t systems
* tests/surrogate-pair: Avoid new failure on systems with
16-bit wchar_t.  Detect the condition and exit before the
otherwise-failing tests.  Remove the now-incorrect in-loop
test for that alternate failure mode.  This was exposed by
testing on gcc119.fsffrance.org, a power8 AIX 7.2 system.

diff --git a/tests/surrogate-pair b/tests/surrogate-pair
--- a/tests/surrogate-pair
+++ b/tests/surrogate-pair
@@ -23,7 +23,8 @@ require_compiled_in_MB_support
 
 fail=0
 
-printf '\360\220\220\205\n' > in || framework_failure_
+s_pair=$(printf '\360\220\220\205')
+printf '%s\n' "$s_pair" > in || framework_failure_
 
 LC_ALL=en_US.UTF-8
 export LC_ALL
@@ -34,13 +35,26 @@ returns_ 1 grep -i anything-else in > out 2>&1 || fail=1
 # Expect no output.
 compare /dev/null out || fail=1
 
+# This must always match, even on a 16-bit-wchar_t system.
+grep . in > out 2> err || fail=1
+
+# On platforms where wchar_t is only 16 bits, wchar_t cannot represent
+# the character encoded in 'in'.
+
+# On such old systems the above prints nothing on stdout and a diagnostic
+# on stderr.  In that case, return early; otherwise, the following tests
+# would all fail.
+io_pair=$(cat out):$(cat err)
+case $io_pair in
+  :'grep: in: binary file matches') Exit $fail;;
+  $s_pair:) ;;
+  *) fail_ "unexpected output: $io_pair"; fail=1;;
+esac
+
 # Also test whether a surrogate-pair in the search string works.
 for opt in '' -i -E -F -iE -iF; do
   grep --file=in $opt in > out 2>&1 || fail=1
-
-  # On platforms where wchar_t is only 16 bits, wchar_t cannot represent
-  # the character encoded in 'in', so accept that behavior too.
-  compare out in || compare /dev/null out || fail=1
+  compare out in || fail=1
 done
 
 Exit $fail
