tests: extend some tests to use -M.

diff --git a/tests/symlink b/tests/symlink
--- a/tests/symlink
+++ b/tests/symlink
@@ -33,38 +33,41 @@ for recursion in '' -r -R
 do
   for files in '' '*'
   do
-    case $recursion,$files in
-      -R,* | *,'*') expected_status=2 ;;
-      *) expected_status=0 ;;
-    esac
+    for threads in '' -M
+    do
+      case $recursion,$files in
+        -R,* | *,'*') expected_status=2 ;;
+        *) expected_status=0 ;;
+      esac
 
-    (cd dir && grep $recursion '^' $files <a ) >grepout
-    test $? -eq $expected_status || fail=1
+      (cd dir && grep $threads $recursion '^' $files <a ) >grepout
+      test $? -eq $expected_status || fail=1
 
-    case $recursion,$files in
-      ,)
-         exp='a\n' ;;
-      ,'*' | -R,)
-         exp='a:a\nb:b\nc:a\n' ;;
-      -r,)
-         exp='a:a\nb:b\n' ;;
-      -r,'*')
-         exp='a:a\nb:b\nc:a\nd/a:a\nd/b:b\n' ;;
-      -R,'*')
-         exp='a:a\nb:b\nc:a\nd/a:a\nd/b:b\nd/c:a\n' ;;
-      *)
-         framework_failure_ ;;
-    esac
+      case $recursion,$files in
+        ,)
+           exp='a\n' ;;
+        ,'*' | -R,)
+           exp='a:a\nb:b\nc:a\n' ;;
+        -r,)
+           exp='a:a\nb:b\n' ;;
+        -r,'*')
+           exp='a:a\nb:b\nc:a\nd/a:a\nd/b:b\n' ;;
+        -R,'*')
+           exp='a:a\nb:b\nc:a\nd/a:a\nd/b:b\nd/c:a\n' ;;
+        *)
+           framework_failure_ ;;
+      esac
 
-    printf "$exp" >exp || framework_failure_
+      printf "$exp" >exp || framework_failure_
 
-    LC_ALL=C sort grepout >out-t || fail=1
+      LC_ALL=C sort grepout >out-t || fail=1
 
-    # Ignore "Binary file d matches" on systems for which
-    # reading from a directory actually succeeds.
-    grep -v Binary out-t > out; case $? in 0|1) ;; *) fail=1;; esac
+      # Ignore "Binary file d matches" on systems for which
+      # reading from a directory actually succeeds.
+      grep -v Binary out-t > out; case $? in 0|1) ;; *) fail=1;; esac
 
-    compare exp out || fail=1
+      compare exp out || fail=1
+    done
   done
 done
 
