tests: avoid unwarranted test failure on *BSD-based systems
* tests/word-delim-multibyte (e_acute): Use a more portable
representation of e-acute.  Reported by Bruno Haible.

diff --git a/tests/word-delim-multibyte b/tests/word-delim-multibyte
--- a/tests/word-delim-multibyte
+++ b/tests/word-delim-multibyte
@@ -5,12 +5,13 @@
 
 require_en_utf8_locale_
 
-echo 'é' > in || framework_failure_
+e_acute=$(printf '\303\251')
+echo "$e_acute" > in || framework_failure_
 LC_ALL=en_US.UTF-8
 export LC_ALL
 
 fail=0
-grep '\<é' in > out 2>err || fail=1
+grep '\<$e_acute' in > out 2>err || fail=1
 
 compare out in || fail=1
 compare err /dev/null || fail=1
